name: Setup Hathora CLI
description: 'Setting up the Hathora CLI'
inputs:
  appId:
    required: true
    type: string
  token:
    required: true
    type: string
  version:
    default: 'main'
    type: string
runs:
  using: "composite"
  steps:
    - name: Setup CLI
      run: |
        if [ "${{ inputs.version }}" == "main" ]; then
          curl -s https://raw.githubusercontent.com/hathora/ci/main/install.sh | sh
        else
          INSTALL_DIR="/usr/local/bin"
          BINARY_NAME="hathora"
          echo "Downloading $BINARY_NAME version ${{ inputs.version }}..."

          if [ "$(uname -m)" == "aarch64" ]; then
             curl -s -L -o $BINARY_NAME https://github.com/hathora/ci/releases/download/${{ inputs.version }}/hathora-linux-arm64
          elif [ "$(uname -m)" == "x86_64" ]; then
             curl -s -L -o $BINARY_NAME https://github.com/hathora/ci/releases/download/${{ inputs.version }}/hathora-linux-amd64
          else
             echo "Unsupported architecture: $(uname -m)"
             exit 1
          fi
             
          chmod +x $BINARY_NAME
          sudo mv $BINARY_NAME $INSTALL_DIR
        fi
        export HATHORA_TOKEN=${{ inputs.token }}
        export HATHORA_APP_ID=${{ inputs.appId }}
      shell: bash