name: Setup Hathora CLI
description: 'Setting up the Hathora CLI'
inputs:
  appId:
    required: true
    type: string
  token:
    required: true
    type: string
  version:
    default: 'main'
    type: string
runs:
  using: "composite"
  steps:
    - name: Setup CLI
      run: |
        if [ "${{ github.event.inputs.version }}" == "main" ]; then
          curl -s https://raw.githubusercontent.com/hathora/ci/main/install.sh | sh
        else
          INSTALL_DIR="/usr/local/bin"
          BINARY_NAME="hathora"
          curl -s -L -o "$BINARY_NAME" "$DOWNLOAD_URL" "https://github.com/hathora/ci/releases/download/${{ github.event.inputs.version }}/hathora-linux-arm64"
          chmod +x "${BINARY_NAME}"
            mv "${BINARY_NAME}" "${INSTALL_DIR}}"
        fi
        curl -s https://raw.githubusercontent.com/hathora/ci/main/install.sh | sh
        export HATHORA_TOKEN=${{ github.event.inputs.token }}
        export HATHORA_APP_ID=${{ github.event.inputs.appId }}
      shell: bash